# Generated by Django 4.1.1 on 2022-09-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_Weather_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=15)),
                ('city_weather_condn', models.CharField(max_length=30)),
                ('city_time', models.CharField(max_length=15)),
                ('city_date', models.CharField(max_length=15)),
            ],
        ),
    ]
