# Generated by Django 4.1.1 on 2022-09-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infilect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=15)),
            ],
        ),
    ]
